# Generated by Django 4.1 on 2022-08-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hzapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anket',
            name='state',
            field=models.PositiveIntegerField(default=0, verbose_name='Статус'),
            preserve_default=False,
        ),
    ]
